name: CI

on:
  push:
    branches:
      - '*'
      - 'renovate/**'
  pull_request:
  workflow_dispatch:

jobs:
  linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
        with:
          submodules: 'recursive'

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install Rust Toolchain
        run: rustup update && rustup target add armv7-linux-androideabi aarch64-linux-android i686-linux-android x86_64-linux-android && rustup component add rustfmt clippy

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./app/src/main/rust"

      - name: Rustfmt Check
        working-directory: ./app/src/main/rust
        run: cargo fmt --all -- --check

      - name: Clippy Check
        working-directory: ./app/src/main/rust
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true

      - name: Spotless Check
        run: ./gradlew spotlessCheck

      - name: CMake Cache
        uses: actions/cache@v3
        with:
          path: |
            app/.cxx
            app/src/main/cpp/nettle/nettle
          key: ${{ runner.os }}-cmake-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-cmake-

      - name: Gradle Build
        run: ./gradlew assembleRelease

      - name: Update ARM64
        uses: actions/upload-artifact@v3
        with:
          name: arm64-v8a-${{ github.sha }}
          path: app/build/outputs/apk/release/app-arm64-v8a-release.apk

      - name: Update x86_64
        uses: actions/upload-artifact@v3
        with:
          name: x86_64-${{ github.sha }}
          path: app/build/outputs/apk/release/app-x86_64-release.apk

      - name: Update ARM32
        uses: actions/upload-artifact@v3
        with:
          name: armeabi-v7a-${{ github.sha }}
          path: app/build/outputs/apk/release/app-armeabi-v7a-release.apk

      - name: Update x86
        uses: actions/upload-artifact@v3
        with:
          name: x86-${{ github.sha }}
          path: app/build/outputs/apk/release/app-x86-release.apk

      - name: Update mapping
        uses: actions/upload-artifact@v3
        with:
          name: mapping-${{ github.sha }}
          path: app/build/outputs/mapping/release/mapping.txt
          retention-days: 5
