name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Install Rust Toolchain
        run: rustup update && rustup target add armv7-linux-androideabi aarch64-linux-android i686-linux-android x86_64-linux-android && rustup component add rustfmt clippy

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./app/src/main/rust"

      - name: Rustfmt Check
        working-directory: ./app/src/main/rust
        run: cargo fmt --all -- --check

      - name: Clippy Check
        working-directory: ./app/src/main/rust
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-encryption-key: ${{ secrets.GradleEncryptionKey }}
          gradle-home-cache-cleanup: true

      - name: Spotless Check
        run: ./gradlew spotlessCheck

      - name: CMake Cache
        uses: actions/cache@v4
        with:
          path: app/.cxx
          key: cmake-${{ hashFiles('gradle/libs.versions.toml', 'app/build.gradle.kts', 'app/src/main/cpp/CMakeLists.txt') }}
          restore-keys: cmake-

      - name: Build
        run: ./gradlew assembleRelease

      - name: Upload ARM64
        uses: actions/upload-artifact@v4
        with:
          name: arm64-v8a-${{ github.sha }}
          path: app/build/outputs/apk/release/app-arm64-v8a-release.apk

      - name: Upload x86_64
        uses: actions/upload-artifact@v4
        with:
          name: x86_64-${{ github.sha }}
          path: app/build/outputs/apk/release/app-x86_64-release.apk

      - name: Upload ARM32
        uses: actions/upload-artifact@v4
        with:
          name: armeabi-v7a-${{ github.sha }}
          path: app/build/outputs/apk/release/app-armeabi-v7a-release.apk

      - name: Upload x86
        uses: actions/upload-artifact@v4
        with:
          name: x86-${{ github.sha }}
          path: app/build/outputs/apk/release/app-x86-release.apk

      - name: Upload mapping
        uses: actions/upload-artifact@v4
        with:
          name: mapping-${{ github.sha }}
          path: app/build/outputs/mapping/release/mapping.txt

      - name: Upload native debug symbols
        uses: actions/upload-artifact@v4
        with:
          name: native-debug-symbols-${{ github.sha }}
          path: app/build/outputs/native-debug-symbols/release/native-debug-symbols.zip
