name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Gradle Build
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: assembleDefaultRelease

      - name: Upload apk
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: app/build/outputs/apk/default/release/app-default-release.apk

      - name: Upload mapping
        uses: actions/upload-artifact@v4
        with:
          name: mapping
          path: app/build/outputs/mapping/defaultRelease/mapping.txt

      - name: Generate dump
        run: ./gradlew assembleDefaultRelease -Dorg.gradle.caching=false -Dcom.android.tools.r8.dumpinputtofile=dump.zip --no-daemon

      - name: Upload dump
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dump
          path: dump.zip
