name: Releases

on:
  push:
    tags:
      - "*"

jobs:
  linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
        with:
          submodules: 'recursive'

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install Rust Toolchain
        run: rustup update && rustup target add armv7-linux-androideabi aarch64-linux-android i686-linux-android x86_64-linux-android

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./app/src/main/rust"

      - name: CMake Cache
        uses: actions/cache@v3
        with:
          path: |
            app/.cxx
            app/src/main/cpp/nettle/nettle
          key: ${{ runner.os }}-cmake-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-cmake-

      - name: Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleRelease

      - name: Rename Apks
        run: |
          mv app/build/outputs/apk/defaultOss/release/app-default-oss-universal-release.apk EhViewer-default-oss-universal.apk
          mv app/build/outputs/apk/defaultOss/release/app-default-oss-arm64-v8a-release.apk EhViewer-default-oss-arm64-v8a.apk
          mv app/build/outputs/apk/defaultOss/release/app-default-oss-x86_64-release.apk EhViewer-default-oss-x86_64.apk
          mv app/build/outputs/apk/defaultOss/release/app-default-oss-x86-release.apk EhViewer-default-oss-x86.apk
          mv app/build/outputs/apk/defaultOss/release/app-default-oss-armeabi-v7a-release.apk EhViewer-default-oss-armeabi-v7a.apk
          mv app/build/outputs/mapping/defaultOssRelease/mapping.txt default-oss-mapping.txt
          mv app/build/outputs/native-debug-symbols/defaultOssRelease/native-debug-symbols.zip default-oss-native-debug-symbols.zip

          mv app/build/outputs/apk/defaultGms/release/app-default-gms-universal-release.apk EhViewer-default-gms-universal.apk
          mv app/build/outputs/apk/defaultGms/release/app-default-gms-arm64-v8a-release.apk EhViewer-default-gms-arm64-v8a.apk
          mv app/build/outputs/apk/defaultGms/release/app-default-gms-x86_64-release.apk EhViewer-default-gms-x86_64.apk
          mv app/build/outputs/apk/defaultGms/release/app-default-gms-x86-release.apk EhViewer-default-gms-x86.apk
          mv app/build/outputs/apk/defaultGms/release/app-default-gms-armeabi-v7a-release.apk EhViewer-default-gms-armeabi-v7a.apk
          mv app/build/outputs/mapping/defaultGmsRelease/mapping.txt default-gms-mapping.txt
          mv app/build/outputs/native-debug-symbols/defaultGmsRelease/native-debug-symbols.zip default-gms-native-debug-symbols.zip

          mv app/build/outputs/apk/marshmallowOss/release/app-marshmallow-oss-universal-release.apk EhViewer-marshmallow-oss-universal.apk
          mv app/build/outputs/apk/marshmallowOss/release/app-marshmallow-oss-arm64-v8a-release.apk EhViewer-marshmallow-oss-arm64-v8a.apk
          mv app/build/outputs/apk/marshmallowOss/release/app-marshmallow-oss-x86_64-release.apk EhViewer-marshmallow-oss-x86_64.apk
          mv app/build/outputs/apk/marshmallowOss/release/app-marshmallow-oss-x86-release.apk EhViewer-marshmallow-oss-x86.apk
          mv app/build/outputs/apk/marshmallowOss/release/app-marshmallow-oss-armeabi-v7a-release.apk EhViewer-marshmallow-oss-armeabi-v7a.apk
          mv app/build/outputs/mapping/marshmallowOssRelease/mapping.txt marshmallow-oss-mapping.txt
          mv app/build/outputs/native-debug-symbols/marshmallowOssRelease/native-debug-symbols.zip marshmallow-oss-native-debug-symbols.zip

          mv app/build/outputs/apk/marshmallowGms/release/app-marshmallow-gms-universal-release.apk EhViewer-marshmallow-gms-universal.apk
          mv app/build/outputs/apk/marshmallowGms/release/app-marshmallow-gms-arm64-v8a-release.apk EhViewer-marshmallow-gms-arm64-v8a.apk
          mv app/build/outputs/apk/marshmallowGms/release/app-marshmallow-gms-x86_64-release.apk EhViewer-marshmallow-gms-x86_64.apk
          mv app/build/outputs/apk/marshmallowGms/release/app-marshmallow-gms-x86-release.apk EhViewer-marshmallow-gms-x86.apk
          mv app/build/outputs/apk/marshmallowGms/release/app-marshmallow-gms-armeabi-v7a-release.apk EhViewer-marshmallow-gms-armeabi-v7a.apk
          mv app/build/outputs/mapping/marshmallowGmsRelease/mapping.txt marshmallow-gms-mapping.txt
          mv app/build/outputs/native-debug-symbols/marshmallowGmsRelease/native-debug-symbols.zip marshmallow-gms-native-debug-symbols.zip

      - name: Releases
        uses: softprops/action-gh-release@v1
        with:
          body: Bump Version
          files: |
            EhViewer-default-oss-universal.apk
            EhViewer-default-oss-arm64-v8a.apk
            EhViewer-default-oss-x86_64.apk
            EhViewer-default-oss-x86.apk
            EhViewer-default-oss-armeabi-v7a.apk
            default-oss-mapping.txt
            default-oss-native-debug-symbols.zip

            EhViewer-default-oss-universal.apk
            EhViewer-default-oss-arm64-v8a.apk
            EhViewer-default-oss-x86_64.apk
            EhViewer-default-oss-x86.apk
            EhViewer-default-oss-armeabi-v7a.apk
            default-oss-mapping.txt
            default-oss-native-debug-symbols.zip

            EhViewer-marshmallow-oss-universal.apk
            EhViewer-marshmallow-oss-arm64-v8a.apk
            EhViewer-marshmallow-oss-x86_64.apk
            EhViewer-marshmallow-oss-x86.apk
            EhViewer-marshmallow-oss-armeabi-v7a.apk
            marshmallow-oss-mapping.txt
            marshmallow-oss-native-debug-symbols.zip

            EhViewer-marshmallow-gms-universal.apk
            EhViewer-marshmallow-gms-arm64-v8a.apk
            EhViewer-marshmallow-gms-x86_64.apk
            EhViewer-marshmallow-gms-x86.apk
            EhViewer-marshmallow-gms-armeabi-v7a.apk
            marshmallow-gms-mapping.txt
            marshmallow-gms-native-debug-symbols.zip
