name: Releases

on:
  push:
    tags:
      - "*"

jobs:
  linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
        with:
          submodules: 'recursive'

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install Rust Toolchain
        run: rustup update && rustup target add armv7-linux-androideabi aarch64-linux-android i686-linux-android x86_64-linux-android

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./app/src/main/rust"
          cache-all-crates: "true"

      - name: CMake Cache
        uses: actions/cache@v3
        with:
          path: app/.cxx
          key: ${{ runner.os }}-cmake-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-cmake-

      - name: Build Cache
        uses: actions/cache@v3
        with:
          path: app/build
          key: ${{ runner.os }}-build-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-build-

      - name: Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleRelease

      - name: Rename Apks
        run: |
          cp app/build/outputs/apk/release/app-universal-release.apk app/build/outputs/apk/release/EhViewer-universal.apk
          cp app/build/outputs/apk/release/app-arm64-v8a-release.apk app/build/outputs/apk/release/EhViewer-arm64-v8a.apk
          cp app/build/outputs/apk/release/app-x86_64-release.apk app/build/outputs/apk/release/EhViewer-x86_64.apk
          cp app/build/outputs/apk/release/app-x86-release.apk app/build/outputs/apk/release/EhViewer-x86.apk
          cp app/build/outputs/apk/release/app-armeabi-v7a-release.apk app/build/outputs/apk/release/EhViewer-armeabi-v7a.apk

      - name: Releases
        uses: softprops/action-gh-release@v1
        with:
          body: Bump Version
          files: |
            app/build/outputs/apk/release/EhViewer-universal.apk
            app/build/outputs/apk/release/EhViewer-arm64-v8a.apk
            app/build/outputs/apk/release/EhViewer-x86_64.apk
            app/build/outputs/apk/release/EhViewer-x86.apk
            app/build/outputs/apk/release/EhViewer-armeabi-v7a.apk
            app/build/outputs/mapping/release/mapping.txt
