name: Releases

on:
  push:
    tags:
      - "*"

jobs:
  linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
        with:
          submodules: 'recursive'

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install Rust Toolchain
        run: rustup update && rustup target add armv7-linux-androideabi aarch64-linux-android i686-linux-android x86_64-linux-android

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./app/src/main/rust"

      - name: CMake Cache
        uses: actions/cache@v3
        with:
          path: |
            app/.cxx
            app/src/main/cpp/nettle/nettle
          key: ${{ runner.os }}-cmake-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-cmake-

      - name: Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleRelease

      - name: Rename Apks
        run: |
          mv app/build/outputs/apk/default/release/app-default-universal-release.apk EhViewer-default-universal.apk
          mv app/build/outputs/apk/default/release/app-default-arm64-v8a-release.apk EhViewer-default-arm64-v8a.apk
          mv app/build/outputs/apk/default/release/app-default-x86_64-release.apk EhViewer-default-x86_64.apk
          mv app/build/outputs/apk/default/release/app-default-x86-release.apk EhViewer-default-x86.apk
          mv app/build/outputs/apk/default/release/app-default-armeabi-v7a-release.apk EhViewer-default-armeabi-v7a.apk
          mv app/build/outputs/mapping/defaultRelease/mapping.txt default-mapping.txt
          mv app/build/outputs/native-debug-symbols/defaultRelease/native-debug-symbols.zip default-native-debug-symbols.zip
          mv app/build/outputs/apk/marshmallow/release/app-marshmallow-universal-release.apk EhViewer-marshmallow-universal.apk
          mv app/build/outputs/apk/marshmallow/release/app-marshmallow-arm64-v8a-release.apk EhViewer-marshmallow-arm64-v8a.apk
          mv app/build/outputs/apk/marshmallow/release/app-marshmallow-x86_64-release.apk EhViewer-marshmallow-x86_64.apk
          mv app/build/outputs/apk/marshmallow/release/app-marshmallow-x86-release.apk EhViewer-marshmallow-x86.apk
          mv app/build/outputs/apk/marshmallow/release/app-marshmallow-armeabi-v7a-release.apk EhViewer-marshmallow-armeabi-v7a.apk
          mv app/build/outputs/mapping/marshmallowRelease/mapping.txt marshmallow-mapping.txt
          mv app/build/outputs/native-debug-symbols/marshmallowRelease/native-debug-symbols.zip marshmallow-native-debug-symbols.zip

      - name: Releases
        uses: softprops/action-gh-release@v1
        with:
          body: Bump Version
          files: |
            EhViewer-default-universal.apk
            EhViewer-default-arm64-v8a.apk
            EhViewer-default-x86_64.apk
            EhViewer-default-x86.apk
            EhViewer-default-armeabi-v7a.apk
            default-mapping.txt
            default-native-debug-symbols.zip
            EhViewer-marshmallow-universal.apk
            EhViewer-marshmallow-arm64-v8a.apk
            EhViewer-marshmallow-x86_64.apk
            EhViewer-marshmallow-x86.apk
            EhViewer-marshmallow-armeabi-v7a.apk
            marshmallow-mapping.txt
            marshmallow-native-debug-symbols.zip
